name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE: test_db
      MYSQL_PASSWORD: test

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.3'
        extensions: mbstring, intl pdo_mysql
        ini-values: post_max_size=256M, short_open_tag=On
        tools: phpunit
  
    - name: Test with phpunit
      run: php index.php
